name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
  - upload-video:
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test videos
          path: cypress/videos
          retention-days: 14